# -*- coding: utf-8 -*-
"""GT03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zKNxOpKU66VrqL8QONlRdZ-W76SN1bP
"""

!pip -q install -U transformers accelerate scikit-learn pandas matplotlib

import os
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from transformers import AutoTokenizer, AutoModelForCausalLM
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

SAVE_DIR = "/content/pink_elephant_v3_results"
os.makedirs(SAVE_DIR, exist_ok=True)

print("SAVE_DIR =", SAVE_DIR)
print("CUDA available =", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU =", torch.cuda.get_device_name(0))

MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",
    device_map="auto",
    trust_remote_code=True
)
model.eval()

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("Loaded:", MODEL_NAME)
print("Model device:", model.device)

concept_pairs = [
    ("ピンクのゾウ", "青い鳥"),
    ("紫のワニ", "赤い傘"),
    ("空飛ぶトースター", "白いネコ"),
    ("緑の月", "黄色い花"),
    ("巨大なスプーン", "小さな犬"),
    ("透明な魚", "茶色の机"),
]

def build_prompts(x, y):
    return {
        "affirm":  f"{x}を想像して、1文で説明してください。",
        "negate":  f"{x}を想像しないでください。別のものを1文で説明してください。",
        "replace": f"{x}ではなく、{y}を想像して、1文で説明してください。",
        "control": f"{y}を想像して、1文で説明してください。",
    }

def normalize_vec(v, eps=1e-8):
    norm = np.linalg.norm(v)
    if norm < eps:
        return v
    return v / norm

def cosine_sim(a, b):
    a = a.reshape(1, -1)
    b = b.reshape(1, -1)
    return float(cosine_similarity(a, b)[0, 0])

def contains_text(text, target):
    return int(target in text)

def get_hidden_states_generation_start(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True).to(model.device)

    with torch.no_grad():
        outputs = model(
            **inputs,
            output_hidden_states=True,
            use_cache=False
        )

    hidden_states = outputs.hidden_states
    attention_mask = inputs["attention_mask"][0].detach().cpu().numpy()
    last_pos = int(attention_mask.sum() - 1)

    layer_vecs = []
    for hs in hidden_states:
        # hs: [1, seq_len, hidden_dim]
        vec = hs[0, last_pos, :].detach().float().cpu().numpy()
        layer_vecs.append(normalize_vec(vec))

    return layer_vecs

def generate_text(prompt, max_new_tokens=50):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if decoded.startswith(prompt):
        gen = decoded[len(prompt):].strip()
    else:
        gen = decoded.strip()

    return gen

def build_anchor_texts(concept):
    return [
        f"{concept}",
        f"{concept}を想像する",
        f"{concept}を思い浮かべる",
        f"{concept}について考える",
        f"{concept}のイメージ",
    ]

def build_anchor_vectors_generation_start(concept):
    texts = build_anchor_texts(concept)
    all_layer_vecs = []

    for t in texts:
        vecs = get_hidden_states_generation_start(t)
        all_layer_vecs.append(vecs)

    n_layers = len(all_layer_vecs[0])
    anchors = []
    for layer_idx in range(n_layers):
        stack = np.stack([v[layer_idx] for v in all_layer_vecs], axis=0)
        anchors.append(normalize_vec(stack.mean(axis=0)))
    return anchors

def score_text_generation_start(text, x_anchor_vectors, y_anchor_vectors):
    vecs = get_hidden_states_generation_start(text)

    sim_x = []
    sim_y = []
    diff_xy = []

    for v, ax, ay in zip(vecs, x_anchor_vectors, y_anchor_vectors):
        sx = cosine_sim(v, ax)
        sy = cosine_sim(v, ay)
        sim_x.append(sx)
        sim_y.append(sy)
        diff_xy.append(sx - sy)

    return sim_x, sim_y, diff_xy

x, y = concept_pairs[0]
prompts = build_prompts(x, y)

x_anchors = build_anchor_vectors_generation_start(x)
y_anchors = build_anchor_vectors_generation_start(y)

for cond, prompt in prompts.items():
    generated = generate_text(prompt, max_new_tokens=50)
    sim_x, sim_y, diff_xy = score_text_generation_start(prompt, x_anchors, y_anchors)

    print("=" * 80)
    print("condition:", cond)
    print("prompt    :", prompt)
    print("generated :", generated)
    print("first 8 diff_xy:", [round(v, 4) for v in diff_xy[:8]])

rows_layers = []
rows_outputs = []

for i, (x, y) in enumerate(concept_pairs):
    print(f"[{i+1}/{len(concept_pairs)}] X={x}, Y={y}")

    prompts = build_prompts(x, y)
    x_anchors = build_anchor_vectors_generation_start(x)
    y_anchors = build_anchor_vectors_generation_start(y)

    for cond, prompt in prompts.items():
        generated = generate_text(prompt, max_new_tokens=50)

        sim_x, sim_y, diff_xy = score_text_generation_start(prompt, x_anchors, y_anchors)

        rows_outputs.append({
            "x": x,
            "y": y,
            "condition": cond,
            "prompt": prompt,
            "generated": generated,
            "contains_x_in_output": contains_text(generated, x),
            "contains_y_in_output": contains_text(generated, y),
        })

        for layer_idx, (sx, sy, dxy) in enumerate(zip(sim_x, sim_y, diff_xy)):
            rows_layers.append({
                "analysis_target": "generation_start",
                "x": x,
                "y": y,
                "condition": cond,
                "layer": layer_idx,
                "sim_to_x_anchor": sx,
                "sim_to_y_anchor": sy,
                "diff_x_minus_y": dxy,
                "prompt": prompt,
                "generated": generated,
            })

df_layers = pd.DataFrame(rows_layers)
df_outputs = pd.DataFrame(rows_outputs)

print(df_layers.shape, df_outputs.shape)
display(df_layers.head())
display(df_outputs.head())

layers_csv = os.path.join(SAVE_DIR, "generation_start_layer_scores_v3.csv")
outputs_csv = os.path.join(SAVE_DIR, "generated_outputs_v3.csv")

df_layers.to_csv(layers_csv, index=False, encoding="utf-8-sig")
df_outputs.to_csv(outputs_csv, index=False, encoding="utf-8-sig")

print(layers_csv)
print(outputs_csv)

mean_diff = (
    df_layers.groupby(["condition", "layer"])["diff_x_minus_y"]
    .mean()
    .reset_index()
)

plt.figure(figsize=(10, 5))
for cond in mean_diff["condition"].unique():
    sub = mean_diff[mean_diff["condition"] == cond]
    plt.plot(sub["layer"], sub["diff_x_minus_y"], label=cond)

plt.axhline(0, linestyle="--")
plt.xlabel("Layer")
plt.ylabel("Mean (sim_to_X - sim_to_Y)")
plt.title("Generation-start analysis: X-Y differential score")
plt.legend()
plt.show()

pivot_diff = mean_diff.pivot(index="layer", columns="condition", values="diff_x_minus_y")

if "negate" in pivot_diff.columns and "control" in pivot_diff.columns:
    diff_nc = pivot_diff["negate"] - pivot_diff["control"]

    plt.figure(figsize=(10, 4))
    plt.plot(diff_nc.index, diff_nc.values)
    plt.axhline(0, linestyle="--")
    plt.xlabel("Layer")
    plt.ylabel("(Negate) - (Control) in X-Y diff")
    plt.title("Extra X-bias under negation at generation start")
    plt.show()

summary_out = (
    df_outputs.groupby("condition")[["contains_x_in_output", "contains_y_in_output"]]
    .mean()
    .reset_index()
)

display(summary_out)

plt.figure(figsize=(7, 4))
plt.bar(summary_out["condition"], summary_out["contains_x_in_output"])
plt.ylabel("Rate")
plt.title("Rate of mentioning X in output")
plt.show()

plt.figure(figsize=(7, 4))
plt.bar(summary_out["condition"], summary_out["contains_y_in_output"])
plt.ylabel("Rate")
plt.title("Rate of mentioning Y in output")
plt.show()

for cond in ["affirm", "negate", "replace", "control"]:
    print("=" * 80)
    print("CONDITION:", cond)
    display(df_outputs[df_outputs["condition"] == cond][["x", "y", "generated"]].head(10))

zip_path = "/content/pink_elephant_v3_results.zip"
!zip -r -q {zip_path} {SAVE_DIR}
print("created:", zip_path)

files.download("/content/pink_elephant_v3_results.zip")